envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: bacs350-demo
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: Mark-Seaman/BACS350
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bacs350-demo-app
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: 03/Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Mark-Seaman/BACS350
  name: bacs350-demo-static
  routes:
  - path: /static
  source_dir: 03/Superhero/static
